name: main

on:
  push:
    branches:
      - main
      - b12

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      
      - name: Build zip files for lambda
        working-directory: python/test
        run: |
          pip install -r requirements.txt
          zip -r .
          ls
      
