name: main

on:
  push:
    branches:
      - main
      - feat/**

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - run: |
          echo "issue_id=$(echo "${{ github.event.ref }}" | grep -o -E "[a-zA-Z0-9,\.\_\-]+-[0-9]+" | tr '[:upper:]' '[:lower:]')" 
          echo "issue_id=$(echo "${{ github.event.ref }}" | grep -o -E "[a-zA-Z0-9,\.\_\-]+-[0-9]+" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
