name: main

on:
  push:
    branches:
      - main
      - feat/**

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "summary": "Pipeline Failure",
              "sections": [{
                "activityTitle": "failure on x!",
                "facts": [{
                  "name": "Triggered by:",
                  "value": "${{ github.actor }}"
                }]
              }],
                "markdown": true,
              "potentialAction": [{
                "@type": "OpenUri",
                "name": "View Failed Run",
                "targets": [{ "os": "default", "uri": "abc" }]
              }]
            }