name: main

on:
  push:
    branches:
      - main
      - feat/**

jobs:
  E2E_TEST:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - run: echo "hi"
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "themeColor": "0076D7",
              "summary": "${{job.status}} running ${{github.job}} job",
              "sections": [{
                  "activityTitle": "${{job.status}} running ${{github.job}} job",
                  "activitySubtitle": "Repository: ${{ github.repository }}",
                  "activityImage": "https://raw.githubusercontent.com/Skitionek/notify-microsoft-teams/master/icons/${{job.status}}.png",
                  "facts": [{
                      "name": "Triggered by:",
                      "value": "${{ github.actor }}"
                  }, {
                      "name": "Environment:",
                      "value": "dev"
                  }, {
                      "name": "Status:",
                      "value": "${{job.status}}"
                  }],
                  "markdown": true
              }],
              "potentialAction": [
                {
                  "@type": "OpenUri",
                  "name": "View Repository",
                  "targets": [{
                      "os": "default",
                      "uri": "${{ github.server_url }}/${{ github.repository }}"
                  }]
                }, 
                {
                  "@type": "OpenUri",
                  "name": "View Job",
                  "targets": [{
                      "os": "default",
                      "uri": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }]
                } 
              ]
            }
