name: main

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo two
      - run: |
          cat main.txt