name: main

on:
  push:
    branches:
      - main

jobs:
  job1:
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        include:
          - environment: 'prod-na'
          - environment: 'prod-eu'
    uses: ./.github/workflows/sub.yml
    secrets: inherit
    with:
      env: ${{ matrix.environment }}

