name: main

on:
  push:
    branches:
      - main
      - b12

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Notify Dynatrace on Build
        run: |
          curl --location '${{ secrets.DT_URL }}/api/v2/events/ingest' \
              --header 'Authorization: Api-Token ${{ secrets.DT_TOKEN }}' \
              --header 'Content-Type: application/json; charset=utf-8' \
              --fail-with-body \
              --data '{
                "eventType": "CUSTOM_INFO",
                "title": "Switchboard: DEV Build Version",
                "properties": {
                  "app.version":"1.62.1.6"
                  }
              }'
