name: main

on:
  push:
    branches:
      - main
      - feat/**

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - run: dwsf
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
              "@type": "MessageCard",
              "@context": "http://schema.org/extensions",
              "themeColor": "0076D7",
              "summary": "${{job.status}} on ${{github.job}}",
              "sections": [{
                  "activityTitle": "${{job.status}} on ${{github.job}}",
                  "activitySubtitle": "On ${{ github.repository }}",
                  "activityImage": "https://adaptivecards.io/content/cats/3.png",
                  "facts": [{
                      "name": "triggered by",
                      "value": "${{ github.actor }}"
                  }, {
                      "name": "Environment",
                      "value": "dev"
                  }, {
                      "name": "Status",
                      "value": "${{job.status}}"
                  }],
                  "markdown": true
              }],
              "potentialAction": [ 
              {
                  "@type": "View",
                  "name": "View Job",
                  "targets": [{
                      "os": "default",
                      "uri": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }]
              }]
            }
