name: main

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        deploy: ['vrs', 'vri']
        env: ['prod-na', 'prod-eur']

    steps:
      - run: echo ${{matrix.env}}
      - run: echo ${{matrix.deploy}}
