name: main

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        env: ['prod-na']
        deploy: ['vrs', 'vri']
    steps:
      - run: echo ${{matrix.env}}
      - run: echo ${{matrix.deploy}}
      