name: main

on:
  push:
    branches:
      - main
      - feat/**

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - run: dwsf
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: always()
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            {
            "@type": "MessageCard",
            "@context": "http://schema.org/extensions",
            "themeColor": "0076D7",
            "summary": "Larry Bryant created a new task",
            "sections": [{
                "activityTitle": "Larry Bryant created a new task",
                "activitySubtitle": "On Project Tango",
                "activityImage": "https://adaptivecards.io/content/cats/3.png",
                "facts": [{
                    "name": "Assigned to",
                    "value": "Unassigned"
                }, {
                    "name": "Due date",
                    "value": "Mon May 01 2017 17:07:18 GMT-0700 (Pacific Daylight Time)"
                }, {
                    "name": "Status",
                    "value": "Not started"
                }],
                "markdown": true
            }],
            "potentialAction": [{
                "@type": "ActionCard",
                "name": "Add a comment",
                "inputs": [{
                    "@type": "TextInput",
                    "id": "comment",
                    "isMultiline": false,
                    "title": "Add a comment here for this task"
                }],
                "actions": [{
                    "@type": "HttpPOST",
                    "name": "Add comment",
                    "target": "https://learn.microsoft.com/outlook/actionable-messages"
                }]
            }, {
                "@type": "ActionCard",
                "name": "Set due date",
                "inputs": [{
                    "@type": "DateInput",
                    "id": "dueDate",
                    "title": "Enter a due date for this task"
                }],
                "actions": [{
                    "@type": "HttpPOST",
                    "name": "Save",
                    "target": "https://learn.microsoft.com/outlook/actionable-messages"
                }]
            }, {
                "@type": "OpenUri",
                "name": "Learn More",
                "targets": [{
                    "os": "default",
                    "uri": "https://learn.microsoft.com/outlook/actionable-messages"
                }]
            }, {
                "@type": "ActionCard",
                "name": "Change status",
                "inputs": [{
                    "@type": "MultichoiceInput",
                    "id": "list",
                    "title": "Select a status",
                    "isMultiSelect": "false",
                    "choices": [{
                        "display": "In Progress",
                        "value": "1"
                    }, {
                        "display": "Active",
                        "value": "2"
                    }, {
                        "display": "Closed",
                        "value": "3"
                    }]
                }],
                "actions": [{
                    "@type": "HttpPOST",
                    "name": "Save",
                    "target": "https://learn.microsoft.com/outlook/actionable-messages"
                }]
            }]
            }